### ISSUE TITLE
Getting 7.1 work inside ASH with VB Cable

### ISSUE THREAD

**Issue by ad2003** [ShanonPearce/ASH-Toolset#2]
Hi there! Nice project! I was just playing around a bit with the ASH Toolkit and was wondering how I can make it use my VB HiFi Cable setup instead of the Stereo Soundcard. I am using HeSuVi with VB HifiCable and VB AUDIO ASIO Bridge and it works perfectly fine for 7.1 content. When I start ASH, I can use it to get binaural audio for Stereo and it works, too-  but not for 7.1 / 5.1. When I switch to 5.1./7.1 and mute L and R nothing comes from the rear speakers, center.  When I export a binaural file, it also shows up in HeSuVi, but the rear speakers are not loud enough. 
Do you have an idea how I can make this work or is this even possible? **_Thanks_** for your work!

**Comment by ShanonPearce** [comment]
Hi, I did my testing of 7.1 content using voicemeeter as my playback device. I used the quick configuration tab of the toolset and had equalizer APO installed on the voicemeeter input playback device which was configured in the windows sound settings for 7.1.
In theory there shouldn't be any issues with 7.1 as long as the playback device supports 7.1 channels. However, I haven't used VB HifiCable in a long while so Ill try that out and see if I come across any issues.

Just to confirm did you face the same problem using quick configuration tab and also exporting to hesuvi? Both methods should produce the same surround effect unless something has gone wrong. Ill also check again in hesuvi in case something broke in the export.

**Comment by ad2003** [comment]
Hi Shanon, thanks for the quick reply. I switched from voice meter a long time ago due to better latency with my setup (almost 0). I was following this 1st post to set my confic up and it works fine [sourceforge](https://sourceforge.net/p/hesuvi/discussion/general/thread/ce7c354dd7/)

I tried the quick configuration tab and also the export method - I attached a sample file for hesuvi - 7.1 works, but the rear speaker are way too low, even if I try to add gain in the quick config. The pre-created files from here (https://github.com/ShanonPearce/ASH-Listening-Set/tree/main/HeSuVi/hrir) work perfectly fine, too. My favorite is the _Studio_B.wav :). I have to say, that I am not a pro on this so I was happy to find those hrir files - so if ASH doesn't work with my setup - I am okay with it. I was just wondering if I did something wrong in my setup. Please don't bother to find the error, because I can find a solution for my setup - just not with ASH Toolset in real time. I thought maybe there are settings somewhere where I have to specify my sound device. I am quite a noob when it comes to HRIR and BRIR. I love the ability to simulate 7.1 on headphones and I have a lot of respect for people who really understand it. Due to the different setup options, it is not easy to find the right way. But it's almost a miracle that you can get 7.1 with VB Cable on a simple laptop soundcard. 

 
[_KU-100-THK_Outdoors-B_2.0dB_Flat_In-Ear-High.zip](https://github.com/user-attachments/files/17932675/_KU-100-THK_Outdoors-B_2.0dB_Flat_In-Ear-High.zip)

**Comment by ShanonPearce** [comment]
I will definitely give VB HiFi Cable a go as well as it looks like it will also have the added benefit of better latency. 

I've also tested HeSuVi exports again and I am able to get 7.1 working with my current set up so the hesuvi export function seems to be working correctly. 

A few simple things to confirm:
1) your playback device (hifi cable input in this case) is configured for 7.1 audio in windows?
2) In ASH toolset, you don't have any binaural simulations activated in the quick configuration tab when using hesuvi? If you had any active simulations, that would result in a doubling up of processing in equalizer apo. In other words the equalizer apo configuration editor shouldn't have both ASH toolset config and hesuvi config active at the same time.
<img width="347" alt="image" src="https://github.com/user-attachments/assets/6f39f481-c28a-4a2f-b11f-d4b17b117c24">

3) if using quick configuration tab, the channel configuration section is also set up for 7.1 like below? I should also point out that it doesn't perform any upmixing to 7.1 in the current release.
<img width="452" alt="image" src="https://github.com/user-attachments/assets/c42ee3c1-5518-435b-a2f0-133396add846">

**Comment by ad2003** [comment]
Ah! I got it thank you! I didn't know to turn off hesuvi in the config in APO. Now it works. Perfect!
