### ISSUE TITLE
Most of the HATS have more gain on left channel than on the right

### ISSUE THREAD

**Issue by conordy** [ShanonPearce/ASH-Toolset#3]
I've noticed that when selecting some HATS they have more gain on the left. Here's the graph of true stereo impulse that I exported with these parameters:
B&K-4128C-MMHR_Audio-Lab-A_2.0dB_Flat_In-Ear-High
![image](https://github.com/user-attachments/assets/0ea95bcc-39e7-4eed-ad16-400155777ca0)

**Comment by ShanonPearce** [comment]
Hi, I had a look and compared the left and right responses of different HATS. It seems that the differences in gains of left and right sides comes from the asymmetry of the HATS or the setups used to perform the HRTF measurements. 

To get around this, I will include an option in the next release to force symmetry by mirroring either the left or right side of the HATS, resulting in identical gains in left and right source directions.

**Comment by conordy** [comment]
Thanks!

**Comment by NekoAlosama** [comment]
With v3.0.2, I don't see any mirroring with the setting enabled, though the separation between the left and right channels are reduced. I assume that the mirroring would make the waveform for the summed left channel to equal to the summed right channel. Oddly, it seems that the mirroring just made slightly different versions of the unmirrored BRIR.

Current setup:
![image](https://github.com/user-attachments/assets/6be5f989-b154-460c-8ef3-784bedbd7b6c)

Disabled:
![image](https://github.com/user-attachments/assets/77a6bacd-cae3-4bbf-97cc-a57b6d5a0ae3)

Forced Left:
![image](https://github.com/user-attachments/assets/8d36b626-4c06-47a3-870a-7d95237dd970)

Forced Right:
![image](https://github.com/user-attachments/assets/9c9650cf-b0e1-43a3-96b5-d4ca3113fb87)
